basePath: /api/v3
definitions:
  ds.City:
    properties:
      name:
        type: string

      description:
        type: string
      id:
        type: integer
      image:
        type: string
      is_delete:
        type: boolean
      radius:
        type: number
      distance:
        type: number
      gravity:
        type: number
      type:
        type: string
    type: object
host: 127.0.0.1
info:
  contact:
    email: drakenchef@gmail.com
    name: API Support
    url: https://github.com/Drakenchef
  description: ASM flights
  license:
    name: AS IS (NO WARRANTY)
  title: AMS
  version: "1.0"
paths:
  /planets:
    get:
      description: Get a list of planets with optional filtering by planet name.
      parameters:
        - description: Planet name for filtering
          in: query
          name: Марс
          type: string
      produces:
        - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/ds.Planet'
            type: array
      summary: Get a list of planets
      tags:
        - planets
schemes:
  - http
swagger: "2.0"